---
deployment:
  tasks:
    # 1. Update this to your exact full path:
    - export DEPLOYPATH=/home/joeconstanti/public_html/madebyjoe.co/

    # 2. Copy everything (except .git) into that folder:
    - /bin/cp -R . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git